### PR TITLE
Upgrade to Elasticsearch 7.4

### PR DESCRIPTION
**Pull request by mattjw**
- 👍 Branch successfully builds the plugin for Elasticsearch 7.4, as zip file.
- 👍 Checked that vector scoring query works in Elasticsearch 7.4.

### CODE REVIEW

**Comment by mattjw** [comment]
Update: Verified to be working with a deployed Elasticsearch 7.4 instance.

**Comment by mattjw** [comment]
CCI build failing due to pre-existing issue. Namely, JVM version mismatch.

**Review by andrassy — APPROVED** [review]
LGTM! Shame about the CCI build. :(

**Comment by andrassy** [comment]
I tried CCI with an openjdk-13 image (see https://github.com/cookpad/fast-cosine-similarity/blob/andrassy/cci-openjdk-13-buster/.circleci/config.yml and https://app.circleci.com/jobs/github/cookpad/fast-cosine-similarity/8) - not compatible with Gradle 5 - awaiting Gradle 6. We'd have to create a custom openjdk-12 image for CCI. Given we're probably going to abandon in favour of dense vectors I don't think this is worth the effort.

**Pull request merged**
